default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: root
  password: root

development:
  <<: *default
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  database: qiita_clone_development

test:
  <<: *default
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  database: qiita_clone_test

production:
  <<: *default
  database: qiita_clone_production
  username: qiita_clone
  password: <%= ENV['QIITA_CLONE_DATABASE_PASSWORD'] %>